[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/auth/adminlogin"
  to = "/.netlify/functions/admin-login"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
